apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main
  namespace: apps
spec:
  project: default
  source:
    repoURL: https://github.com/EmVee-hub/kube-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
